# this is test pipeline for php
# Install Composer using commands
tasks:
  unit-test:
    runner: razorci/php:7.4
    steps:
    - checkout
    - commands:
      - uptime
      - php --version
      - sudo curl -sS https://getcomposer.org/installer | php
      - php composer.phar
      - php composer.phar update --no-scripts
      - cp .env.example .env
      - php artisan key:generate
      - php artisan config:cache
      - php artisan test
